name: master

on:
  push:
    branches: [ master ]

jobs:
  run-test-cases:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Java 8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: test
        run: mvn test
